package flores.familytree;

import com.google.gson.Gson;
import flores.familytree.Node;
import flores.familytree.Tree;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.TreeView;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

//ESTUDIANTE : FLORES MONTENEGRO ALVARO MAURICIO
//REGISTRO   : 215015827

/**
 *
 * @author Olaf
 */
public class JInterface extends javax.swing.JFrame {

    Tree ft;

    /**
     * Creates new form JInterface
     */

    public JInterface() { // we inicialize the Family Tree getting a written(in the form) couple married.
        initComponents();
        ft = new Tree(tfmale.getText());
        ft.marry(tfmale.getText(), tffemale.getText());
        fillTreeView();
//        jtview.setModel(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmarry = new javax.swing.JButton();
        tfmale = new javax.swing.JTextField();
        tffemale = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnaddchild = new javax.swing.JButton();
        tfchild = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtview = new javax.swing.JTree();
        btnsave = new javax.swing.JButton();
        btnopen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmarry.setBackground(new java.awt.Color(204, 204, 204));
        btnmarry.setText("CASAR");
        btnmarry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarryActionPerformed(evt);
            }
        });

        tfmale.setText("Adan");

        tffemale.setText("Eva");
        tffemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffemaleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mujer");

        btnaddchild.setText("ADDHIJO");
        btnaddchild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddchildActionPerformed(evt);
            }
        });

        tfchild.setText("Cain");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("solo varon");

        jtview.setBackground(new java.awt.Color(204, 204, 204));
        jtview.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon("E:\\Universidad\\ED2\\ProyectoED2\\FamilyTree\\src\\main\\java\\Icons\\MacFamilyTree_30181.png"))); // NOI18N
        jtview.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtview.setName(""); // NOI18N
        jtview.setScrollsOnExpand(false);
        jScrollPane2.setViewportView(jtview);

        btnsave.setText("Guardar");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnopen.setText("Abrir");
        btnopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Archivo");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ESTUDIANTE : FLORES MONTENEGRO ALVARO MAURICIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("REGISTRO : 215015827");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnmarry, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tffemale, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(tfmale))
                        .addGap(146, 146, 146)
                        .addComponent(btnaddchild, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfchild, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(btnsave)
                                .addGap(27, 27, 27)
                                .addComponent(btnopen, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfmale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmarry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddchild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfchild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave)
                    .addComponent(btnopen))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tffemale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tffemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffemaleActionPerformed

    private void btnmarryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarryActionPerformed
        if (ft == null) { // it marries a couple if the tree is empty.
            String male = tfmale.getText();
            String female = tffemale.getText();
            if (!male.equals("") && !female.equals("")) {
                ft = new Tree(male);
                ft.marry(male, female);
            }
        } else { //if the Tree isnt empty , it gets the string male and female and marry them.
            String male = tfmale.getText();
            String female = tffemale.getText();
            if (!male.equals("") && !female.equals("")) {
                ft.marry(male, female);
            }
        }
        fillTreeView();

    }//GEN-LAST:event_btnmarryActionPerformed
    private void fillTreeView() { 
        Node root = ft.getRoot(); //we get the Tree from the Tree.class and copy it to the TreeView Root we just created.
        DefaultMutableTreeNode root1 = new DefaultMutableTreeNode(root.visualize()); 
        graphicTree(root, root1);
        DefaultTreeModel model = new DefaultTreeModel(root1);
        jtview.setModel(model);
    }

    private void graphicTree(Node T, DefaultMutableTreeNode TNode) { //IT ALLOWS US TO TRANSFORM OUR TREE IN JTREEVIEW 
        if (T == null) {
            return;
        } else {
            for (int i = 1; i <= T.numberofChildren(); i++) {
                Node h = T.getChild(i);
                if (h == null) {
                    return;
                }
                DefaultMutableTreeNode child = new DefaultMutableTreeNode(h.visualize());
                TNode.add(child);
                graphicTree(h, child);
            }
        }
    }

    private void btnaddchildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddchildActionPerformed
       // this method get the couple for we wanna add a child.
        if(ft == null){
            return;
        }else{ 
        String child = tfchild.getText();
        String couple = tfmale.getText() + "/" + tffemale.getText();
        ft.addChild(couple, child);
        fillTreeView();
        
        }
    }//GEN-LAST:event_btnaddchildActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       //Using dependencies Gson and Methods from Jfile we create a variable savefile and save the actual tree.
        
        JFileChooser chooser = new JFileChooser(); 
        int option = chooser.showSaveDialog(this);

        // 0 option stands for accept in the window
        if (option == JFileChooser.APPROVE_OPTION) {
            File saveFile = chooser.getSelectedFile();
            String path = saveFile.getAbsolutePath();

            Gson gson = new Gson(); //we create a variable Gson 
            String expandTree = gson.toJson(ft);  //we save the tree into Json
            try {
                FileWriter writer = new FileWriter(path); 
                writer.write(expandTree); 

                writer.flush(); //we clean
                writer.close(); //we close

            } catch (IOException ex) {
                Logger.getLogger(JInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int option = chooser.showSaveDialog(this);
        
        if(option == JFileChooser.APPROVE_OPTION){
           File readFile = chooser.getSelectedFile(); 
           String text = "";
            try {
                Scanner reader = new Scanner(readFile);
                while(reader.hasNextLine()){
                    text+= reader.nextLine();
                }
                Gson gson = new Gson();
                ft = gson.fromJson(text, Tree.class);
                fillTreeView(); 
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnopenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddchild;
    private javax.swing.JButton btnmarry;
    private javax.swing.JButton btnopen;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jtview;
    private javax.swing.JTextField tfchild;
    private javax.swing.JTextField tffemale;
    private javax.swing.JTextField tfmale;
    // End of variables declaration//GEN-END:variables
}
